name: Deliver Tokens To Consumer

on:
  push:
    paths:
      - 'build/**'

jobs:
  # Add a job for every additional consumer/application
  deliver_to_vue_application:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deliver Platform Deliverable To Application
      uses: andstor/copycat-action@v3
      with:
        # See documentation: https://docs.github.com/en/actions/reference/encrypted-secrets
        # Set the secret in the "src" repository
        personal_token: ${{ secrets.test_style_dictionary }}
        src_path: build/js/_variables.js
        # Replace with your repository owner. Most likely, this is your GitHub username.
        dst_owner: NeilMcEachin
        dst_repo_name: consume-style-dictionary-github-actions
        dst_path: tokens/_variables.js
        commit_message: Update design tokens
